# Generated by Django 5.2.7 on 2026-04-05 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BarberWeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "barber",
                    models.ForeignKey(
                        limit_choices_to={"is_barber": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["barber", "weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="LunchBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "weekly_schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lunch_break",
                        to="availability.barberweeklyschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["weekly_schedule", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="BarberScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_day_off", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "barber",
                    models.ForeignKey(
                        limit_choices_to={"is_barber": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["barber", "date", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_time__isnull", True),
                                ("is_day_off", True),
                                ("start_time__isnull", True),
                            ),
                            models.Q(
                                ("end_time__isnull", False),
                                ("is_day_off", False),
                                ("start_time__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="schedule_exception_valid_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_day_off", True),
                            ("start_time__lt", models.F("end_time")),
                            _connector="OR",
                        ),
                        name="schedule_exception_start_before_end",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="barberweeklyschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="weekly_schedule_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="barberweeklyschedule",
            constraint=models.UniqueConstraint(
                fields=("barber", "weekday", "start_time", "end_time"),
                name="unique_weekly_schedule_interval_per_barber",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchbreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="lunch_break_start_before_end",
            ),
        ),
    ]
